### ISSUE TITLE
Support for Android

### ISSUE THREAD

**Issue by piedcipher** [olexale/arkit_flutter_plugin#1]
Is it possible to use this plugin for Android apps built using Flutter?

**Comment by olexale** [comment]
Unfortunately, no. ARKit works on iOS mobile devices only.

Try the [ARCore](https://pub.dartlang.org/packages/arcore_plugin) plugin. The framework itself provides similar functionality, but the port is not finished yet.

**Comment by Ali-Azmoud** [comment]
Hi
Can you make a similar library for android with ARCore?
There are some libraries but all of them are limited to basics. someone professional needed for this library

**Comment by dariocavada** [comment]
Did you try the [arcore_flutter_plugin](https://pub.dev/packages/arcore_flutter_plugin) ?

It was inspired by the **arkit_flutter_plugin**... But it does not seem to be very active. The last commit was in December 2019. 

Also I need **ARCore** in Flutter ... (Using Flutter one always expects to be able to deploy apps on both Android and iOS).

I know that **ARCore** is very different from **ARKit** although many of the concepts are shared by both platforms.

**Comment by Ali-Azmoud** [comment]
@dariocavada yeah, but I couldn't find any example of real 3D objects. it's examples are just basic 3d objects like sphere, cylinder and etc...

**Comment by dariocavada** [comment]
In the example folder:
[remote_object.dart](https://github.com/giandifra/arcore_flutter_plugin/blob/master/example/lib/screens/remote_object.dart)

It renders a remote **gltf** object ([Duck.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/raw/master/2.0/Duck/glTF/Duck.gltf)) on plane detection.
