### ISSUE TITLE
Limit and reset nodes - measure example

### ISSUE THREAD

**Issue by OliverNarramore** [olexale/arkit_flutter_plugin#100]
Using the example for measuring distances, is there a way to limit the number of nodes to 2 (drawing a straight line) and then the ability to reset these nodes, should they be placed in the incorrect region?

Thanks :)

**Comment by olexale** [comment]
Hi! 
Yes, it's possible. What have you already tried?

**Comment by olexale** [comment]
Feel free to re-open this issue if you still have this question.
