### ISSUE TITLE
[Question] Is showing a video playback upon image detection supported?

### ISSUE THREAD

**Issue by chatorn-ketsom** [olexale/arkit_flutter_plugin#103]
I'm currently working on a flutter project with a requirement to implement AR for retrieving products' information as video playback. I'm quite new to both flutter and AR, espcially the latter. So I was wondering if this plugin supports what I will do? And if it does, I would appreciate if you could provide an example or a tutorial about it.  Thank you.

**Comment by olexale** [comment]
Hi. From the top of my head:
1. Use Flutter widgets for video playback. You may use the [widget projection sample](https://github.com/olexale/arkit_flutter_plugin/blob/master/example/lib/widget_projection.dart) as a reference. In this sample, I've messed up with the transformation matrix a bit and I don't really have time to fix it, hence PR's are highly appreciated.
2. Use [VideoMaterial](https://developer.apple.com/documentation/realitykit/videomaterial) presented by Apple this year. This option should show much better and reliable results, but it is in beta and is not available for production use yet.
Regards,
Oleksandr

**Comment by chatorn-ketsom** [comment]
> Hi. From the top of my head:
> 
> 1. Use Flutter widgets for video playback. You may use the [widget projection sample](https://github.com/olexale/arkit_flutter_plugin/blob/master/example/lib/widget_projection.dart) as a reference. In this sample, I've messed up with the transformation matrix a bit and I don't really have time to fix it, hence PR's are highly appreciated.
> 2. Use [VideoMaterial](https://developer.apple.com/documentation/realitykit/videomaterial) presented by Apple this year. This option should show much better and reliable results, but it is in beta and is not available for production use yet.
>    Regards,
>    Oleksandr

Hi @olexale. Thank you for your helpful advice. I will try the first option first though yet will also take a look at the VideoMedia as you suggested in case it might be the to-go way regarding the requirement I have that's getting more and more complicated. :) Thanks again.

**Comment by chatorn-ketsom** [comment]
> Hi. From the top of my head:
> 
> 1. Use Flutter widgets for video playback. You may use the [widget projection sample](https://github.com/olexale/arkit_flutter_plugin/blob/master/example/lib/widget_projection.dart) as a reference. In this sample, I've messed up with the transformation matrix a bit and I don't really have time to fix it, hence PR's are highly appreciated.
> 2. Use [VideoMaterial](https://developer.apple.com/documentation/realitykit/videomaterial) presented by Apple this year. This option should show much better and reliable results, but it is in beta and is not available for production use yet.
>    Regards,
>    Oleksandr

Hi @olexale. Thank you for your helpful advice. I will try the first option first though yet will also take a look at the VideoMaterial as you suggested in case it might be the to-go way regarding the requirement I have that's getting more and more complicated. :) Thanks again.

**Comment by jtkeyva** [comment]
I got #1 working but ya the widget is not stable, it wabbles all around and I'm having a hard time fixing it. any news on stabilizing @olexale ? thx
