### ISSUE TITLE
Record Camera feed with Augmentation

### ISSUE THREAD

**Issue by sridevgit** [olexale/arkit_flutter_plugin#105]
Hi,

I was wondering if I can record AR session along with the augmented objects? This is very trivial to our application. If the plugin doesn't support this feature yet, we have to go with unity and AR foundation. Any help is appreciated.

**Comment by olexale** [comment]
Hi,
Please refer to [this issue](https://github.com/olexale/arkit_flutter_plugin/issues/67). This functionality is not related to ARKit directly, hence I suppose that we need to create another plugin, which will wrap arkit view with `SceneKitVideoRecorder`. I do not think it's a good idea to bring 3rd-party dependency in this plugin as far as not every AR app requires camera recording, so I'm closing the issue.
