### ISSUE TITLE
Module 'arkit_plugin' not found

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [olexale/arkit_flutter_plugin#123]
This happens only when trying to build app, not when running, any idea how to fix this?

Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (5 weeks ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5

**Comment by go2hyder** [comment]
I am also having the same issue. @diego-lipinski-de-castro Did you fix it?

**Comment by diego-lipinski-de-castro** [comment]
No. I had to create a new project and copy paste files

**Comment by diego-lipinski-de-castro** [comment]
To be honest I don't remember what I did, I can't even remember if I fixed the problem at all, sorry

**Comment by go2hyder** [comment]
I have done the followings and the issue is fixed

1. Deleted Podfile , Podfile.lock and Pods folder
2. flutter clean
3. flutter build IOS
