### ISSUE TITLE
(question) detectionImageGroupName  - how does it work?

### ISSUE THREAD

**Issue by ashkryab-fl** [olexale/arkit_flutter_plugin#126]
can I specify the parameter "car" and I will get anchors near the car? Or can I use tensorflow with ARkit?
tensorflow has such a model:
```
{
  detectedClass: "hot dog",
  confidenceInClass: 0.123,
  rect: {
    x: 0.15,
    y: 0.33,
    w: 0.80,
    h: 0.27
  }
}
```

**Comment by olexale** [comment]
It is not that simple. You may find a working example [here](https://developer.apple.com/documentation/arkit/content_anchors/recognizing_and_labeling_arbitrary_objects).
It is in native Swift, but I think you'll get the idea and will be able to adjust it according to your requirements.
