### ISSUE TITLE
Arkit multiple anchors

### ISSUE THREAD

**Issue by rubenteste** [olexale/arkit_flutter_plugin#128]
Hi,
I'm testing the arkit, more precisely image detection, but it only allows the detection of one image, how could I add more image anchors to be able to use more than one object?

![imagem](https://user-images.githubusercontent.com/75133022/111465047-84fc6e00-8719-11eb-9de1-eda55e7a1c78.png)

![imagem](https://user-images.githubusercontent.com/75133022/111465246-bf660b00-8719-11eb-8e5a-90cec06190d8.png)

in ARCore
u can use this function to load multiple Images
 
![imagem](https://user-images.githubusercontent.com/75133022/111465497-1966d080-871a-11eb-869d-df8245fe01fa.png)

**Comment by KennyChan94P** [comment]
hi @maxTeste, may i know how did you solve this?
