### ISSUE TITLE
Null Safety Request

### ISSUE THREAD

**Issue by marcoramosw** [olexale/arkit_flutter_plugin#129]
Opening this issue to request Null Safety support, see the [migration guide](https://dart.dev/null-safety/migration-guide)

**Comment by lailai0715** [comment]
Any update on this? Need to use it in my latest flutter2 project

**Comment by lukepighetti** [comment]
This package is rotting, being pinned to SDK 2.11.0 or earlier. We're already in 2.13.0 on dev channel.

**Comment by olexale** [comment]
I've pushed version [1.0.0-nullsafety.0](https://pub.dev/packages/arkit_plugin/versions/1.0.0-nullsafety.0) with null safety to the prerelease channel. All samples worked for me but I would appreciate if you try it in your real projects before I move this version to the stable channel. Thanks in advance!

P.S. your pull requests are welcomed, as always.

**Comment by lukepighetti** [comment]
Thank you very much.

**Comment by olexale** [comment]
No "null safety"-specific issues were reported thus I've pushed the pre-release build to the stable channel.
