### ISSUE TITLE
Image comparison, increase level

### ISSUE THREAD

**Issue by rubenteste** [olexale/arkit_flutter_plugin#130]
hi,
in my multiple image detection i have simliar images.
How can i increase level of comparison for him not to confuse similar images

**Comment by olexale** [comment]
Hi,
This is not about ARKit, but the idea is the same: [one](https://library.vuforia.com/features/images/image-targets/best-practices-for-designing-and-developing-image-based-targets.html), [two](https://vidinoti.github.io/documentation/image-trigger).
TL;DR - you can not have similar images for multiple image detection.

**Comment by rubenteste** [comment]
@olexale is there an way to increment the level of comparison between images?
Somewhere there must be a number where the level of comparison is determined

**Comment by olexale** [comment]
I am not aware of the possibility to configure that.
