### ISSUE TITLE
Archive project for TestFlight

### ISSUE THREAD

**Issue by Octavian-tech** [olexale/arkit_flutter_plugin#131]
Hi, I have a problem, the application works normally when I give it a simple run but when I try to archive it, I get this problem 'module arkit_plugin not found', someone encountered this problem?

**Comment by MinhCuongIT** [comment]
Did you solve this problem?

**Comment by Octavian-tech** [comment]
Yes, the problem was in Xcode, you need to change type of architecture from armv7 to arm64 because AR suports just arm64 this type of architecture

**Comment by MinhCuongIT** [comment]
Thanks for your help!
