### ISSUE TITLE
Custom object example not working in Flutter 2.0

### ISSUE THREAD

**Issue by CaptainRiley** [olexale/arkit_flutter_plugin#141]
Hello, I'm not really sure this is an issue but I thought posting here should help. I am trying to fix this for more than 2 weeks!

I used this **plugin** to display my custom 3D object as in the **example** listed. I made sure that I had no errors and the assets were specified correctly and still my object is not shown. I asked a few people to test the same bug on their devices and it seems it doesn't work to them aswell.

My project is hosted here: **https://github.com/Goncearu/Finer.manager**

The file with my problem is: **arKit.dart.** 
There you will find the file that links my **3D Object** (.dae format) to my app that’s not working. In the same folder can be found another .dae file called "burger".

Can anyone take a look and test on their devices aswell.

Thank you!

**Comment by sikandernoori** [comment]
The Repository Link You Shared is Private.

Can you Make it Public So I can have a look.

**Comment by olexale** [comment]
@CaptainRiley , would you make your project public, so we could take a look?

**Comment by CaptainRiley** [comment]
Hello all, sorry for not responding, I haven't got any email or notification so far from GitHub. I figured it out, I think the documentation can be improved by specifying that the object must be imported into Xcode and after that linked to your code. 
PS: It was the first time trying to use ARKit without knowing how it works in Xcode so sorry for the mess.
