### ISSUE TITLE
ARKitReferenceNode Material. Add Request.

### ISSUE THREAD

**Issue by sikandernoori** [olexale/arkit_flutter_plugin#143]
Hello @olexale.

I see we can change Material of Basic Geometries Like Sphere,Cube etc.

But in real world Problems where we want to Change Material Properties of custom Objects.

Do you have plan for adding Material diffusion and rotation for ARKitReferenceNode.

Thanks !!

**Comment by olexale** [comment]
Hi @sikandernoori,
I'm working on a mechanism that allows overriding parameters (like position, rotation, light, etc.) and material of the geometry of any node by its name. Will that be enough for your task?

**Comment by sikandernoori** [comment]
@olexale that would be Great actually and Yes it would be enough for the project I'm currently working on. 

Looking forward for the update !!

**Comment by olexale** [comment]
Done. Please refer to [the Midas](https://github.com/olexale/arkit_flutter_plugin/blob/master/example/lib/midas_page.dart) sample.

**Comment by olexale** [comment]
Seems like this is not an issue anymore, so I'm closing it.

**Comment by maxTeste** [comment]
I can't wait for the improvements in the mechanics for the rotation and the size of the object so the objects doesn't need to keep resetting
