### ISSUE TITLE
Screen is black

### ISSUE THREAD

**Issue by fignealberto** [olexale/arkit_flutter_plugin#15]
I followed your instructions and testing your code of arkit_flutter_plugin/example/lib. When app enters to hello_world.dart after run

    void onARKitViewCreated(ARKitController arkitController) {
        this.arkitController = arkitController;

        this.arkitController.add(_createSphere());
        this.arkitController.add(_createPlane());
        this.arkitController.add(_createText());
        this.arkitController.add(_createBox());
        this.arkitController.add(_createCylinder());
        this.arkitController.add(_createCone());
        this.arkitController.add(_createPyramid());
        this.arkitController.add(_createTube());
        this.arkitController.add(_createTorus());
        this.arkitController.add(_createCapsule());
     }

Console displays:
   `_platformCallHandler call onError Error`
And the screen becomes black (only appbar is visible).

flutter doctor:
`[✓] Flutter (Channel beta, v1.6.3, on Mac OS X 10.14.5 18F132, locale es-MX)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[!] VS Code (version 1.35.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
`
I'll really appreciate your help on this.

**Comment by olexale** [comment]
Hi @fignealberto ,

First of all, thanks a lot for posting this issue. I appreciate it. That is the only way how I can improve the port.

For now, the plugin calls `onError` when ARKit has initialization problems only. I've added localized description text to the `onError` callback. May I ask you to pull the changes, try one more time, and post the description text here?

Btw, what phone and OS version you're trying to run it on?

Thanks!
Olexandr

**Comment by fignealberto** [comment]
@olexale, thank to you and your efforts.

Sure I'll try the new changes and post here the results asap... right now I'm trying your plugin and another one for Android, so I have kind of a mess with phones and laptops running ditincts OS each one, but I still have two hands only :P

By the way, I am developing with flutter so my goal is to find a way to mix AR solutions in one project... but first, make them work alone, right?

With the results I will post phone and os version.

Have a good day

**Comment by fignealberto** [comment]
Pulled the changes, run again and tap on every option; app keep running but screen still black; in console:
`_platformCallHandler call onError Unsupported configuration`

My phone: iPhone 6Plus iOS 12.3.1

hope this helps :)

**Comment by olexale** [comment]
Hi @fignealberto ,
Unfortunately, your phone does not support ARKit. You need at least iPhone 6s to run AR applications.
