### ISSUE TITLE
snapshot method throws type cast error

### ISSUE THREAD

**Issue by NicolasDurant** [olexale/arkit_flutter_plugin#158]
Hey :wave:, 
the method `snapshot()` on _**ARKitController**_  in the example for creating a snapshot of the **_ARKitSceneView_** throws the following type error:
`'Future<Uint8List?>' is not a subtype of type 'FutureOr<Uint8List>' in type cast`

**Comment by olexale** [comment]
Hi! This should be fixed in `1.0.3`, could you please check that you're using the latest version?

**Comment by NicolasDurant** [comment]
You are absolutely correct, I was on `1.0.1` still! 
Sorry Oleksandr, should have checked that first 😅
