### ISSUE TITLE
Where to put assets file?

### ISSUE THREAD

**Issue by scognito** [olexale/arkit_flutter_plugin#16]
I've successfully loaded the earth example, but the sphere is white (no texture I guess).
The earth.jpg image on the repo is located in the Runner directory, so I've put the same image using Finder in the ios/Runner directory.
The sphere is still white...Am I missing something?
Thanks

EDIT: Nevermind, I had to drag and drop the image on Assets.xcassets in Xcode

**Comment by olexale** [comment]
Hi @scognito,

Sorry for the late response. Glad you've figured it out by yourself!

Thanks!
