### ISSUE TITLE
Is animation supported?

### ISSUE THREAD

**Issue by scognito** [olexale/arkit_flutter_plugin#17]
I didn't see any example about animation....Is it supported or do you fave plan to support it?
Thanks

**Comment by scognito** [comment]
I never used ARKit so I'm completely new.
I've succesfully loaded a model, what I mean is if it is possible to load an animated model (like a breathing animal...)

**Comment by olexale** [comment]
That kind of animations is a bit more complicated. Currently, the plugin doesn't support them, but it is not a problem to add them though. Let's keep this issue opened, and I'll get back to you on this later.

**Comment by Cliche2** [comment]
Hello @olexale ,
did you get to implement the models with animations?

**Comment by olexale** [comment]
Hi guys! Sorry, not yet.

**Comment by olexale** [comment]
Hey guys,
I added an example of a custom model with animations. Please review the [Custom Animations](https://github.com/olexale/arkit_flutter_plugin/blob/master/example/lib/custom_animation_page.dart) sample.
Thanks!

**Comment by olexale** [comment]
Well, no comment, I suppose it works :-)
I'm closing the issue, feel free to re-open it if needed.

Thanks all!

**Comment by aldoaf43** [comment]
Hi!

I want to add my own animation and play it, how I do that?

Thanks!
