### ISSUE TITLE
Can I make a double sided sphere?

### ISSUE THREAD

**Issue by gustavofurtado** [olexale/arkit_flutter_plugin#18]
Hi, thanks for the awesome plugin.
I wonder if can make a double sided sphere, to simulate a 360 view of a photo.
Just like this example: 
https://stackoverflow.com/questions/46423415/how-to-apply-360-video-as-a-texture-in-arkit

Or if you happen to know how I can make this somehow I would be infinitely grateful.

Thank you.

**Comment by olexale** [comment]
Hi @gustavofurtado ,

Thanks! I've just added `doubleSided` property to the `ARKitMaterial` class. I have no time right now to implement a sample, hence may I kindly ask you to pull the latest version and review the functionality?

Thanks again!

**Comment by gustavofurtado** [comment]
Sorry about the lack of knowledge, but it seems I'm not getting an up to date version of the pub, the doubleSided property is still undefined according to vscode. Could you help me?

**Comment by olexale** [comment]
Sure, sorry for confusing you! I haven't pushed an updated version to the pub cause this functionality is not yet tested. You may try the updated version directly from GitHub by modifying `pubspec.yml` like that (have no possibility to test right now, so there might be typos, sorry):
```
dependencies:
  arkit_plugin:
    git:
      url: https://github.com/olexale/arkit_flutter_plugin
```

**Comment by gustavofurtado** [comment]
Hi @olexale I just tested this new feature, it worked perfectly!!
Thank you very much!
If you'd like to I can send the example code I just used.

**Comment by olexale** [comment]
Hi @gustavofurtado,

That would be awesome! If you don't mind, I'll create a sample with it. Or you may add an example by yourself, and I would be glad to merge it ;-)

Thanks!

**Comment by gustavofurtado** [comment]
[Double Sided.txt](https://github.com/olexale/arkit_flutter_plugin/files/3433706/Double.Sided.txt)

I couldn't upload the .dart file, as git did not allow me.
I copied the code to a .txt file so I could send it to you.
My best regards and keep on the awesome work.
