### ISSUE TITLE
Measure distance & angle between detected image and device camera

### ISSUE THREAD

**Issue by hellowtisch** [olexale/arkit_flutter_plugin#19]
Is it possible to obtain the distance and angles for a detected image using the plugin?

Any hint is highly appreciated.
Thanks

**Comment by olexale** [comment]
Yes, it is possible. Please review `image_detection_page` sample - there is an Earth, which position calculates based on image placement.
Thanks!

**Comment by hellowtisch** [comment]
Thank you for your reply. From the native ARKit documentation I found that I would need to get access to the ARCamera object to calculate the distance between a remote point on a plane and the camera plane. Is it possible to access this object from your plugin? I can't seem to find any reference in the code.

**Comment by olexale** [comment]
The implementation hardly depends on your needs. I would set `world alignment` to `camera` and calculated the distance from the origin to the point the same way as it is calculated in `measurement` sample. Below I calculate the distance between origin and feature point in tap event. Play around with `worldAlignment` property to see how it changes the solution (I set `showWorldOrigin` to `true`, to show more visualization).

```dart
import 'package:arkit_plugin/arkit_plugin.dart';
import 'package:flutter/material.dart';
import 'package:vector_math/vector_math_64.dart' as vector;

class CameraDistancePage extends StatefulWidget {
  @override
  _CameraDistancePageState createState() => _CameraDistancePageState();
}

class _CameraDistancePageState extends State<CameraDistancePage> {
  ARKitController arkitController;
  vector.Vector3 lastPosition;
  String distance = '0';

  @override
  void dispose() {
    arkitController?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => Scaffold(
      appBar: AppBar(
        title: const Text('Camera Distance'),
      ),
      body: Stack(
        children: [
          ARKitSceneView(
            enableTapRecognizer: true,
            onARKitViewCreated: onARKitViewCreated,
            showFeaturePoints: true,
            showWorldOrigin: true,
            worldAlignment: ARWorldAlignment.camera,
          ),
          Text(distance, style: Theme.of(context).textTheme.display1),
        ],
      ));

  void onARKitViewCreated(ARKitController arkitController) {
    this.arkitController = arkitController;
    this.arkitController.onARTap = (ar) {
      final point =
          ar.firstWhere((o) => o.type == ARKitHitTestResultType.featurePoint);
      if (point != null) {
        final position = vector.Vector3(
          point.worldTransform.getColumn(3).x,
          point.worldTransform.getColumn(3).y,
          point.worldTransform.getColumn(3).z,
        );
        setState(() {
          distance =
              _calculateDistanceBetweenPoints(vector.Vector3.zero(), position);
        });
      }
    };
  }

  String _calculateDistanceBetweenPoints(vector.Vector3 A, vector.Vector3 B) {
    final length = A.distanceTo(B);
    return '${(length * 100).toStringAsFixed(2)} cm';
  }
}
```

Will that do the trick for your task?

**Comment by hellowtisch** [comment]
That does exactly, what I wanted!

 

Thank you very much!

 

Von: Oleksandr Leuschenko <notifications@github.com>
Antworten an: olexale/arkit_flutter_plugin <reply@reply.github.com>
Datum: Donnerstag, 25. Juli 2019 um 15:45
An: olexale/arkit_flutter_plugin <arkit_flutter_plugin@noreply.github.com>
Cc: hellowtisch <marcel@hellofaservice.de>, Author <author@noreply.github.com>
Betreff: Re: [olexale/arkit_flutter_plugin] Measure distance & angle between detected image and device camera (#19)

 

The implementation hardly depends on your needs. I would set world alignment to camera and calculated the distance from the origin to the point the same way as it is calculated in measurement sample. Below I calculate the distance between origin and feature point in tap event. Play around with worldAlignment property to see how it changes the solution (I set showWorldOrigin to true, to show more visualization).

import 'package:arkit_plugin/arkit_plugin.dart';
import 'package:flutter/material.dart';
import 'package:vector_math/vector_math_64.dart' as vector;
 
class CameraDistancePage extends StatefulWidget {
  @override
  _CameraDistancePageState createState() => _CameraDistancePageState();
}
 
class _CameraDistancePageState extends State<CameraDistancePage> {
  ARKitController arkitController;
  vector.Vector3 lastPosition;
  String distance = '0';
 
  @override
  void dispose() {
    arkitController?.dispose();
    super.dispose();
  }
 
  @override
  Widget build(BuildContext context) => Scaffold(
      appBar: AppBar(
        title: const Text('Camera Distance'),
      ),
      body: Stack(
        children: [
          ARKitSceneView(
            enableTapRecognizer: true,
            onARKitViewCreated: onARKitViewCreated,
            showFeaturePoints: true,
            showWorldOrigin: true,
            worldAlignment: ARWorldAlignment.camera,
          ),
          Text(distance, style: Theme.of(context).textTheme.display1),
        ],
      ));
 
  void onARKitViewCreated(ARKitController arkitController) {
    this.arkitController = arkitController;
    this.arkitController.onARTap = (ar) {
      final point =
          ar.firstWhere((o) => o.type == ARKitHitTestResultType.featurePoint);
      if (point != null) {
        final position = vector.Vector3(
          point.worldTransform.getColumn(3).x,
          point.worldTransform.getColumn(3).y,
          point.worldTransform.getColumn(3).z,
        );
        setState(() {
          distance =
              _calculateDistanceBetweenPoints(vector.Vector3.zero(), position);
        });
      }
    };
  }
 
  String _calculateDistanceBetweenPoints(vector.Vector3 A, vector.Vector3 B) {
    final length = A.distanceTo(B);
    return '${(length * 100).toStringAsFixed(2)} cm';
  }
}
Will that do the trick for your task?

**Comment by hellowtisch** [comment]
I need to reopen this, as I need to keep tracking the distance between the camera and the recognized image, also after the image has beed recognized (i.e. the anchor has been added). Therefore I do need to access what in native arkit would be the ARCamera object, to find out per frame, where the Camera currently located. I tried to use the available methods, but can't seem to solve this.
Is there any way to achieve this with the current plugin version?

Thanks

**Comment by olexale** [comment]
Hi @hellowtisch ,

You don't need to calculate this per frame manually. In case you deal with images here is an example which calculates and updates the distance between the camera and earth image from wiki:
```dart
import 'package:arkit_plugin/arkit_plugin.dart';
import 'package:flutter/material.dart';
import 'package:vector_math/vector_math_64.dart' as vector;

class CameraDistancePage extends StatefulWidget {
  @override
  _CameraDistancePageState createState() => _CameraDistancePageState();
}

class _CameraDistancePageState extends State<CameraDistancePage> {
  ARKitController arkitController;
  vector.Vector3 lastPosition;
  String anchorId;
  String distance = '0';

  @override
  void dispose() {
    arkitController?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => Scaffold(
      appBar: AppBar(
        title: const Text('Camera Distance'),
      ),
      body: Stack(
        children: [
          ARKitSceneView(
            detectionImagesGroupName: 'AR Resources',
            onARKitViewCreated: onARKitViewCreated,
            worldAlignment: ARWorldAlignment.camera,
          ),
          Text(distance, style: Theme.of(context).textTheme.display1),
        ],
      ));

  void onARKitViewCreated(ARKitController arkitController) {
    this.arkitController = arkitController;
    this.arkitController.onAddNodeForAnchor = _handleAddAnchor;
    this.arkitController.onUpdateNodeForAnchor = _handleUpdateAnchor;
  }

  void _handleAddAnchor(ARKitAnchor anchor) {
    if (anchor is ARKitImageAnchor) {
      anchorId = anchor.identifier;
      _updateDistance(anchor);
    }
  }

  void _handleUpdateAnchor(ARKitAnchor anchor) {
    if (anchor.identifier != anchorId) {
      return;
    }
    _updateDistance(anchor);
  }

  void _updateDistance(ARKitAnchor anchor) {
    final position = vector.Vector3(
      anchor.transform.getColumn(3).x,
      anchor.transform.getColumn(3).y,
      anchor.transform.getColumn(3).z,
    );
    setState(() {
      distance =
          _calculateDistanceBetweenPoints(vector.Vector3.zero(), position);
    });
  }

  String _calculateDistanceBetweenPoints(vector.Vector3 A, vector.Vector3 B) {
    final length = A.distanceTo(B);
    return '${(length * 100).toStringAsFixed(2)} cm';
  }
}
```

Hope that helps!

**Comment by olexale** [comment]
Hi @hellowtisch ,
I'm closing the issue. Feel free to re-open it if the proposed solution will not work for you!
Cheers!

**Comment by hellowtisch** [comment]
@olexale: could you add yaw, pitch and roll info of the world image with regards to the camera position and orientation to your example? That would be the solution to my problem.

Cheers

**Comment by davidRuland1234** [comment]
When I set my ARKitSceneView to  worldAlignment: ARWorldAlignment.camera it rotate my images to landscape mode. 
How do I prevent this from happening if I always want my image to be in portrait mode instead of landscape and follows camera position?

**Comment by benMOOVENCY** [comment]
Hi @hellowtisch , 

did you find a solution to obtain camera orientation ?

Cheers

**Comment by marcel-bluestone** [comment]
@benMOOVENCY I think we went a completely different way back then. Unfortunately I don't have the solution at hand...
