### ISSUE TITLE
reset world origin works only one time! 

### ISSUE THREAD

**Issue by kotran88** [olexale/arkit_flutter_plugin#191]
`    func onDispose(_ result:FlutterResult) {
        sceneView.session.pause()
        self.channel.setMethodCallHandler(nil)
        result(nil)
        let configuration = ARWorldTrackingConfiguration()
        sceneView.session.run(configuration, options: [.resetTracking, .removeExistingAnchors])

    }`

I added 
```

   let configuration = ARWorldTrackingConfiguration()
        sceneView.session.run(configuration, options: [.resetTracking, .removeExistingAnchors])
```
above 2line on FlutterArkitView.swift

then, when I want to reset origin anchor, I called arkitcontrolllr.dispose(); 
it really work! but only one time . after reset, I tried to reset anchor again but with no luck

how can I reset world origin anchor more then 1 time.

**Comment by ahmetveysels** [comment]
Hello. I can try but not working. How i can reset ? Thank you.
