### ISSUE TITLE
Can you add geo point of interest AR

### ISSUE THREAD

**Issue by hungtran2492** [olexale/arkit_flutter_plugin#20]

**Comment by hellowtisch** [comment]
I'd say yes you can. You just need to identify where the geo-points should appear in your AR coordinate system, place and render them accordingly?

**Comment by olexale** [comment]
There is no such thing as a geolocation node in ARKit, but there are 3rd party libraries which help to deal with geo points in AR, like https://github.com/ProjectDent/ARKit-CoreLocation.

Indeed this is possible but requires some work to do. I'll be happy to accept a pull request with this functionality, but from my point of view, we have more critical tasks for the plugin for now.

As for today, the answer is no.

Thanks!

**Comment by ventskus-roman** [comment]
If I'm not mistaken, this functionality is available in ARKit 4? https://developer.apple.com/documentation/arkit/argeoanchor
Are there any plans to support this feature in the library?
