### ISSUE TITLE
[Question] Image Targets and tracking 

### ISSUE THREAD

**Issue by tonmoy054** [olexale/arkit_flutter_plugin#21]
Hi there, 
Can we do something like this with this plugin ?
https://library.vuforia.com/articles/Training/Image-Target-Guide

**Comment by tonmoy054** [comment]
Also, if you can, please upload some video tutorials explaining the different examples and features. Which will be really helpful for the beginners.

**Comment by hellowtisch** [comment]
what you are looking for is exactly what the image_detection_page.dart example does. It searches for the earth picture of the wikipedia page and places an anchor at the pictures location, relative to which the virtual globe is shown.

**Comment by olexale** [comment]
Hi @tonmoy054 ,

@hellowtisch is 100% right. You may develop Image Targeting as it is shown in `image_detection` sample. There is only one trick you may miss during testing on your own pictures - it is required to add target images via Xcode, not just placing them in the folder.

Please review that sample and if it works for you feel free to close the issue.

Thanks!

P.S. Thank you, @hellowtisch , for the support!!

**Comment by olexale** [comment]
I suppose you don't have other questions; hence, I'm closing the issue. Feel free to re-open it, if it is needed. Thanks!
