### ISSUE TITLE
black screen instead of scene view

### ISSUE THREAD

**Issue by zaynashahzad24** [olexale/arkit_flutter_plugin#227]
When I start the ARKitSceneView, the view is black with this log error:

"1   arkit_plugin                        0x00000001063fa954 $s12arkit_plugin16FlutterArkitViewC14onMethodCalledyySo0cG4CallC_yypSgXEtF + 800: plugin is not initialized properly"

I've noticed this "black screen" behavior on iOS 16.x.x, but it works as expected on iOS 17.x.x

**Comment by olexale** [comment]
#173 duplicate
