### ISSUE TITLE
NoSuchMethodError on Matrix4.decompose

### ISSUE THREAD

**Issue by hellowtisch** [olexale/arkit_flutter_plugin#24]
Hi Oleksandr 

when using your camera_distance_page.dart example I added some code to obtain quaternions of the detected image anchor (see changes to your code below):
```
 void _handleAddAnchor(ARKitAnchor anchor) {
    if (anchor is ARKitImageAnchor) {
      final imagePosition = anchor.transform.getColumn(3);
      final vector.Matrix4 anchorClone = anchor.transform.clone();

      anchorId = anchor.identifier;
      vector.Vector3 translation, scale;
      vector.Quaternion rotation;
      anchorClone.decompose(translation, rotation, scale);
    _updateDistance();
    }
  }
```

When I try to decompose the transformation matrix the following error get's thrown in platform_channel.dart's _handleAsMethodCall method:

**Debug Output:**

_NoSuchMethodError: The getter '_v3storage' was called on null.
Receiver: null
Tried calling: _v3storage_

MethodCall(didAddNodeForAnchor, {node_name: B547B598-A1F5-4D1C-AC39-D5521560733E, transform: 0.015258 0.999745 -0.016619 0.00000

Is this a bug, or just bad code on my side?
Thanks for looking into this.

Cheers

**Comment by olexale** [comment]
Hi @hellowtisch,
`anchorClone.decompose` will not create variables, but fill the existing ones with new values. 

Hence you may try that:
```dart
      final translation = vector.Vector3.zero();
      final scale = vector.Vector3.zero();
      final rotation = vector.Quaternion.euler(0, 0, 0);
      anchorClone.decompose(translation, rotation, scale);
```

Thanks!
