### ISSUE TITLE
face detection demo not work

### ISSUE THREAD

**Issue by ywszm** [olexale/arkit_flutter_plugin#26]
could you tell me Why does the face detection demo work failed on my iPhone?
Camera failed to use? Display white screen。

**Comment by olexale** [comment]
Hi @ywszm ,
I need more details. Which OS version and iPhone model you use?
Thanks!

**Comment by ywszm** [comment]
iPhone7 ios12.2 Thank you!

**Comment by olexale** [comment]
Face detection functionality requires a device with a front-facing TrueDepth camera. Unfortunately, your device is not supported.

**Comment by ywszm** [comment]
Thank you for your answer！
