### ISSUE TITLE
[Question] How to add multi-Image Detection?

### ISSUE THREAD

**Issue by chaiyootcass** [olexale/arkit_flutter_plugin#27]
Hello, I want to know how to add multi-Image Detection?

because I plan to use it in my senior project to teach children about numeric.

Thank you very much!

**Comment by olexale** [comment]
Hi @chaiyootcass,

The process is completely the same as with single image detection except you’ll need to check the reference image name when image anchor will be detected. There is an appropriate property in ‘ARKitImageAnchor’ for this. 

Good luck with your project! I would be happy to hear about it when you’ll finish the development!

Thanks!

**Comment by chaiyootcass** [comment]
Hi @olexale,

I have one more question.
Do you plan to make it detect a real object or scan 3d object? 

Thanks! ^^

**Comment by olexale** [comment]
I develop features of this plugin by request. Hence if you need real objects detection - feel free to create an issue with more details (samples in swift, some demo data, etc.) and I’ll add it. Thanks!
