### ISSUE TITLE
[Request] Possibility to add ARKit with coreML ?

### ISSUE THREAD

**Issue by chaiyootcass** [olexale/arkit_flutter_plugin#29]
Hello, 

I wanted to integrate ARKit with coreML in my senior project
for example like this https://github.com/hanleyweng/CoreML-in-ARKit
I would like to know if you can add this feature.

Thank you very much!

**Comment by olexale** [comment]
Hello,

I briefly reviewed the sample, and it seems like for the core functionality we only miss a function that returns ARFrame as an image. CoreML though is a different framework, and I suppose it makes sense to keep it as a separate plugin in Flutter as well.

I believe that this sample is out of the ARKit plugin scope. In case you decide to implement it -- feel free to create issues with missed functionality, and I'll add it.

Thanks!
