### ISSUE TITLE
Why is this only iOS!?

### ISSUE THREAD

**Issue by MaterialTime** [olexale/arkit_flutter_plugin#3]

**Comment by olexale** [comment]
I think this question is for Apple, cause ARKit works on iOS devices only.

**Comment by MaterialTime** [comment]
But why not integrate with the Android version of arkit?

**Comment by olexale** [comment]
Because there is no Android version of ARKit. Are we talking about the same framework https://developer.apple.com/arkit/ ?
Maybe ARCore is the framework you're looking for? Here is a plugin for it https://pub.dartlang.org/packages/arcore_plugin.

**Comment by MaterialTime** [comment]
Sorry. I meant Android's *equivalent* of arkit. So that would be arcore. But why not make one Flutter plugin that integrates with both? Isn't that kind of the whole point of Flutter, that it's cross platform?

**Comment by olexale** [comment]
In the future, we'll end with that. However, it is required to develop bindings to ARKit and ARCore first.

**Comment by MaterialTime** [comment]
Okay. Just thought it was strange that there are two different packages for iOS and Android.
