### ISSUE TITLE
App rejection by TrueDepth API

### ISSUE THREAD

**Issue by Nickkun** [olexale/arkit_flutter_plugin#30]
Can I choose to use the TrueDepth API?

I'm sorry to hear that you recently received a decline in the review process for your app using this plugin.

The app was rejected because of the code in the TrueDepth API included in arkit_plugin. Since the app uses only the AR View feature, the TrueDepth API is not required, but it appears to be rejected because it is included in the plugin.

Can't we update the TrueDepth API so that we can pick up the answer from the Apple Review Team?

---------------------------------------
Guideline 2.5.1-Performance-Software Requirements

During review, we found that your app includes TrueDepth APIs. However, we were not able to locate any features in your app that use TrueDepth APIs.

Next steps

If your app does not include any features that use TrueDepth APIs, please remove them from your app.

If your app uses the Unity ARKit plugin, it would be appropriate to update to the latest version (https://forum.unity.com/threads/submitting-arkit-apps-to-appstore-without-face-tracking.504572/ # post-3297235), which includes a setting that allows you to exclude TrueDepth APIs.

If your app does include features that use TrueDepth APIs, please reply to this message in Resolution Center to provide information on how to locate them.

Please see attached screenshots for details.

**Comment by olexale** [comment]
Hah.. That sounds like an interesting problem :-)

I'll restructure the plugin to make it possible to pick only required parts of ARKit. Meanwhile, I propose two solutions:
1. Fork the plugin, remove everything related to TrueDepth API, and compile the app with your version. (**I recommend this**)
2. Submit a privacy policy with the App Store and reference it within your app, even if you don't need it.

Thanks for this issue!

**Comment by Nickkun** [comment]
Sounds Great! @olexale 
Thank you and I'll try to your suggestion.

**Comment by scognito** [comment]
Is there some fork available? I didn't found one and never made swift code or flutter plugins

**Comment by olexale** [comment]
Hey folks,
Sorry for the late reply, I'm super busy right now. I've created a separate branch without Face-related functionality. Just removed it from the iOS side, hence on the Flutter side the API is visible, but should not work.
Could you please check?
```yaml
dependencies:
  arkit_plugin:
    git:
      url: git://github.com/olexale/arkit_flutter_plugin.git
      ref: noTrueDepth
```
Thanks in advance!

**Comment by Nickkun** [comment]
> Hey folks,
> Sorry for the late reply, I'm super busy right now. I've created a separate branch without Face-related functionality. Just removed it from the iOS side, hence on the Flutter side the API is visible, but should not work.
> Could you please check?
> 
> ```yaml
> dependencies:
>   arkit_plugin:
>     git:
>       url: git://github.com/olexale/arkit_flutter_plugin.git
>       ref: noTrueDepth
> ```
> 
> Thanks in advance!

We've replaced the plug-in based on your feedback and submitted it for review.
I will reply again as soon as the judging results come out

**Comment by Nickkun** [comment]
> Hey folks,
> Sorry for the late reply, I'm super busy right now. I've created a separate branch without Face-related functionality. Just removed it from the iOS side, hence on the Flutter side the API is visible, but should not work.
> Could you please check?
> 
> ```yaml
> dependencies:
>   arkit_plugin:
>     git:
>       url: git://github.com/olexale/arkit_flutter_plugin.git
>       ref: noTrueDepth
> ```
> 
> Thanks in advance!

Wow! Your app has been approved and updated in the App Store. Thank you!

**Comment by olexale** [comment]
Hey folks,
I figured out how we can use the plugin without splitting it into two different implementations. Please refer to [this part of README](https://github.com/olexale/arkit_flutter_plugin/blob/master/README.md#before-you-go-to-appstore). After you modify the `Podfile` you're safe to go with the master branch again.
Thanks for raising this issue!

**Comment by a7medlord** [comment]
> Hey folks, Sorry for the late reply, I'm super busy right now. I've created a separate branch without Face-related functionality. Just removed it from the iOS side, hence on the Flutter side the API is visible, but should not work. Could you please check?
> 
> ```yaml
> dependencies:
>   arkit_plugin:
>     git:
>       url: git://github.com/olexale/arkit_flutter_plugin.git
>       ref: noTrueDepth
> ```
> 
> Thanks in advance!

  I need this version because the last one makes conflict with firebase google plugin. when i use swfit flag disable_true_depth_api
