### ISSUE TITLE
add support for android TargetPlatform

### ISSUE THREAD

**Issue by iamprakash13** [olexale/arkit_flutter_plugin#31]
i tried running the code with android device. it shows 
`TargetPlatform.android is not supported by this plugin`

please resolve this soon, make it available in andriod devices too.

**Comment by olexale** [comment]
I'll gladly do this as soon as Apple will add support for Android devices in ARKit.

**Comment by iamprakash13** [comment]
when will they add andriod support? is there any alternative way of doing ar in android with flutter.
new plugin? 
basically how you created this plugin? can i design plugin for andriod myself?

**Comment by olexale** [comment]
I suppose not in the nearest future.

For Android, you may use [ARCore plugin](https://github.com/giandifra/arcore_flutter_plugin) by Gian Marco Di Francesco.

Sure you may. Here is a [great manual](https://flutter.dev/docs/development/packages-and-plugins/developing-packages) about plugins.

**Comment by heyme2gm** [comment]
Hey sir, Now it's 2021... Can we see to implement this plugin in android devices too, It will be great to use in android devices as well.

BTW Thanks for this plugin.
