### ISSUE TITLE
Feature request - camera node

### ISSUE THREAD

**Issue by mtwillet** [olexale/arkit_flutter_plugin#33]
@olexale I am trying to build a "Floor Target" that moves around horizontal planes based on the cameras position. I see how I can get distances off of hit test using the camera world alignment, but is there a way I can get orientational information of the phone?

**Comment by olexale** [comment]
Hi @mtwillet ,
Sorry, I am not sure I get it. Could you please specify which exactly additional information is needed?

**Comment by olexale** [comment]
I'm closing this issue as no additional details provided. Feel free to reopen it.

**Comment by miles-au** [comment]
Hey @olexale, I just recently stumbled on this plugin. Thanks to you and the team for all the work that's been put into this! 

I think the feature I'm looking for is similar to what @mtwillet is asking. I'm looking for something similar to Apple's Measure app, where the line is drawn in real time to wherever the centre of your camera is. It's basically a real-time preview of where your measurement is going to be.

Here's what the Apple Measure app looks like: https://support.apple.com/en-us/HT208924

Would there be a way to do this?
