### ISSUE TITLE
How to detect two or more images (same image) on a screen?

### ISSUE THREAD

**Issue by chaiyootcass** [olexale/arkit_flutter_plugin#34]
![S__28008451](https://user-images.githubusercontent.com/30156796/68089635-75baae80-fe9d-11e9-81cd-c4fb211dd458.jpg)

Sorry, I don't know about native IOS.
Can you add function to return array ARKitAnchor? 

Thank you very much.

**Comment by olexale** [comment]
Hi! Regret to say, but it seems like this is not possible. According to Apple ([link](https://developer.apple.com/documentation/arkit/detecting_images_in_an_ar_experience)):

> ARKit adds an image anchor to a session exactly once for each reference image in the session configuration’s detectionImages array.

Hence there is a one-to-one relationship between image anchor and a reference image.
