### ISSUE TITLE
Slow: Pan /Scale and Rotate

### ISSUE THREAD

**Issue by anoop4real** [olexale/arkit_flutter_plugin#36]
First of all thanks for this plugin, I could follow it very well, below is one issue which is bothering me.
In the manipulation sample, pinch and pan detection are quite slow... once you add the box try a few pinch... move your finger away from screen and try pinching again, I had to try atleast 5-6 times to grab the box.  I tried in iPhoneXR as well as iPhone 6s, the behaviour is same in both. May be we need to add simultaneous recognition??

```
    func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool {
        return true
    }
```

**Comment by olexale** [comment]
Hey! 

Thank you for this proposition! I just added the requested change. Hope it works better now.

Kind regards
