### ISSUE TITLE
[Request] Possibility to add measure feature ?

### ISSUE THREAD

**Issue by jakoby12** [olexale/arkit_flutter_plugin#4]
Hi!

I'm new in Flutter and I wanted to integrate ARKit in my project. Thanks to you it's possible!

I'm very interested by this measure feature, and I would like to know if you can add this feature.

Thank you in advance!

**Comment by olexale** [comment]
Hi!

That sounds like a great idea! Measure sample is on my plate. So let's keep this issue opened, I will get back as soon as I finish.

Thanks! ;)

**Comment by AxelAmbert** [comment]
It would be realy great.
I'm excited to see that !

**Comment by olexale** [comment]
Hey guys! I am glad to say that it works now :)
Please review `Distance tracking` and `Measure` samples.

**Comment by jakoby12** [comment]
Hi!

I've tested `Distance tracking` and `Measure`, and I didn't find any bugs.
Maybe it's better to print the value on top of the screen to have a better read.
And also it can be more precise if there is a cursor to add points because.

But it's already good!

Thanks for your great job!

**Comment by olexale** [comment]
Hi!

Do you have an idea of how it should look in terms of API design? Will something like a `forceCenterScreenForTaps` option, which will force ARKit to use the center of the screen as a tap position, do the trick?

Thanks!

**Comment by jakoby12** [comment]
Yep I guess it will be working with that trick. Or maybe a button which set points in the center of the screen. I don't know if it's much easier, what do you think?

**Comment by olexale** [comment]
I've added `forceUserTapOnCenter` flag. You may add an icon (or plus sign) above the center of `ARKitSceneView` widget to make it clear for the user where taps are processing. 
Could you please check?

Thanks!

**Comment by jakoby12** [comment]
I couldn't add an icon to make it clear but all points are placed on the center of the screen when I tap everywhere. 

Great jobs!

**Comment by olexale** [comment]
Great! You may place a static icon in the center of the AR scene like that:
```dart
        Stack(fit: StackFit.expand, children: [
          ARKitSceneView(...),
          const Icon(Icons.add, color: Colors.white, size: 32)
        ]
```

Thanks for the testing!
