### ISSUE TITLE
How to check ARKit supported device

### ISSUE THREAD

**Issue by toonztudio** [olexale/arkit_flutter_plugin#40]
Hi,

I want to show alert box when user's devices are not supported this ARKit plugin.
How can check? 

Thank you very much for an awesome plugin.

**Comment by toonztudio** [comment]
Oh!
I think i found onError in  ARKitSceneView class, hope this is correct :)

**Comment by olexale** [comment]
Hi @toonztudio ,

You'll definitely get an error in `onError`, but this approach might lead to bad user experience. I would recommend checking the iOS version before trying to establish an AR session. The [device_info](https://pub.dev/packages/device_info) plugin might be in hand for that.

I will update the README file with this recommendation.

Thanks!

**Comment by toonztudio** [comment]
@olexale OK, I will check it. thank you for your great work.
