### ISSUE TITLE
How to move object with PanRecognizer?

### ISSUE THREAD

**Issue by toonztudio** [olexale/arkit_flutter_plugin#41]
Hi,

I try to implement _onPanHandler to move plane object with this code but not working.
Could you please give me some advice?

`void _onPanHandler(List<ARKitNodePanResult> pan) {
    for (var panNode in pan) {
      final node = nodes.firstWhere((n) => n.name == panNode.nodeName);
      if (node != null) {
        final old = node.position.value;
        final newMoveX = panNode.translation.x;
        final newMoveY = panNode.translation.y;
        node.position.value = vector.Vector3(newMoveX, newMoveY, old.z);
      }
    }
  }`

**Comment by YuriOsipov** [comment]
Translation function using for rotation only
For moving object ARKitNodePanResult has to provide the location property
So need to add support location features in arkit_node_pan_result.dart and "FlutterArkitView+GesutreRecognizer.swift"

**Comment by LucasTejero** [comment]
if you are using 0.4.1 or higher you can use updateAtTime with a gesturedetector to achieve that


`GestureDetector(
      onPanEnd: (detail) {
        tapping = false;
      },
      onPanUpdate: (detail) {
        tapping = true;
        _x = detail.globalPosition.dx / MediaQuery.of(context).size.width;
        _y = detail.globalPosition.dy / MediaQuery.of(context).size.height;
      },)`

`this.arkitController.updateAtTime=(time){
                        if (busy == false) {
                          busy = true;
                          this.arkitController.performHitTest(x: _x, y: _y).then((results) {
                            if (results.isNotEmpty) {
                                final ARKitTestResult point = results.firstWhere(
                                      (o) => o.type == ARKitHitTestResultType.featurePoint);
                              final position = vector.Vector3(
                                point.worldTransform.getColumn(3).x,
                                point.worldTransform.getColumn(3).y,
                                point.worldTransform.getColumn(3).z,
                              );
                              GeometryNode.position.value = position;
                            }
                            busy = false;
                          });
                        }
                      };`

**Comment by olexale** [comment]
Thanks @LucasTejero !
