### ISSUE TITLE
How to use ARPlaneDetection.horizontalAndVertical

### ISSUE THREAD

**Issue by ukieTux** [olexale/arkit_flutter_plugin#42]
I tried to change plane detection to ARPlaneDetection.horizontalAndVertical but nothing happen

**Comment by olexale** [comment]
Hi @ukieTux ,
What would you expect to change? Could you please provide more details?
Thanks!

**Comment by ukieTux** [comment]
i think if i'm implement ARPlaneDetection.horizontalAndVertical it can automatically detect object in vertical or horizontal

**Comment by olexale** [comment]
Indeed. There is a sample `occlusion_page` with `ARPlaneDetection.horizontalAndVertical`. Is it working for you? And one more question - which OS version are you using?

**Comment by olexale** [comment]
Hey! I think I've got what was the problem you faced to. Please try the latest version of the plugin (from the GitHub directly, not from the pub).
