### ISSUE TITLE
Add custom object

### ISSUE THREAD

**Issue by jeanmatthieud** [olexale/arkit_flutter_plugin#44]
Hello,

Thank you very much for your library. I'm not used to develop for iOs, so having the ability to use ARKit with flutter is awesome.
I need to add custom objects in the scene. I maybe missed something, but I didn't find any sample with custom objects. Its seems that's it's possible with ARKit (importing dae scenes).

Is it possible with the current implementation or is it something to come?

Best regards,

JM

**Comment by olexale** [comment]
Hi @jeanmatthieud ,

There is a [Custom Object](https://github.com/olexale/arkit_flutter_plugin/blob/master/example/lib/custom_object_page.dart) sample, which looks like what you're looking for.

Thank you!

**Comment by jeanmatthieud** [comment]
Hi !
I don't know how I missed that.
I will try it soon.

Thanks !
