### ISSUE TITLE
Face mask

### ISSUE THREAD

**Issue by scognito** [olexale/arkit_flutter_plugin#45]
Thanks for this awesome library, it works flwlessy.
The AR  Face demo with wireframe is awesome.
I know it is not a bug, but I want to add texture on the face, using a canonical image like this one:
[https://developers.google.com/ar/images/canonical-face-texture-photoshop.jpg](https://developers.google.com/ar/images/canonical-face-texture-photoshop.jpg)
Is it possbile? Thank you!

**Comment by olexale** [comment]
Hey,
Please refer to the `FaceDetectionPage` sample. Instead of
```dart
final material = ARKitMaterial(fillMode: ARKitFillMode.lines);
```
You may create the material with your own texture.

Kind regards
