### ISSUE TITLE
Support for reading QR Codes and barcodes

### ISSUE THREAD

**Issue by chrissy25** [olexale/arkit_flutter_plugin#47]
Is it possible to detect and read an QR-Code or an barcode with the plugin?

**Comment by olexale** [comment]
No. AR is not about barcodes. You may find dozen of barcode scanners on pub - https://pub.dev/packages?q=barcode

**Comment by chrissy25** [comment]
Okay, I am fully aware of that AR is not about barcodes or QR codes, but we would like to show content based on the QR code, which will be detected by the camera. So similiar to an image detection, but based on the content within QR code and as it is available for images, I am curiuos if also QR code detection would be supported.

**Comment by olexale** [comment]
In that case, QR code is no different from any other anchor image. You may follow the `Earth` sample.

**Comment by javiermedina-c** [comment]
> Okay, I am fully aware of that AR is not about barcodes or QR codes, but we would like to show content based on the QR code, which will be detected by the camera. So similiar to an image detection, but based on the content within QR code and as it is available for images, I am curiuos if also QR code detection would be supported.

Hi, do you find a solution?
