### ISSUE TITLE
Check if TrueDepth camera is supported

### ISSUE THREAD

**Issue by scognito** [olexale/arkit_flutter_plugin#48]
I know we can use device_info plugin, but there is [this function](https://developer.apple.com/documentation/arkit/arconfiguration/2923553-issupported) you can incorporate to check easily if the camera is supported.
Using device_info I have to check manually "machine" string and compare with the supported ones and update the function each time a new model comes out.
Thanks

**Comment by olexale** [comment]
Hey!

I've added `ARKitPlugin.checkConfiguration` method. You may review the `check_support_page.dart` sample for details. I hope it helps.

Thanks!
