### ISSUE TITLE
ARKitPosition isn't defined

### ISSUE THREAD

**Issue by jakoby12** [olexale/arkit_flutter_plugin#5]
Hi! 

In your function which we can see in your usage
```
void onARKitViewCreated(ARKitController arkitController) {
    this.arkitController = arkitController;
    this.arkitController.addSphere(ARKitSphere(
      position: ARKitPosition(0, 0, -0.5),
      radius: 0.1,
    ));
  }
```

So, to resolve this issue, you juste have to replace  
`position: ARKitPosition(0, 0, -0.5),` 
to
`position: ARKitVector3(0, 0, -0.5),`

I know it's a minor issue but I hope it's can help anyone who is beginner.

Thanks for your work!

**Comment by olexale** [comment]
Nice catch! I'll rewrite the whole `Usage` section as soon as API becomes more or less stable.
