### ISSUE TITLE
Object tracking and anchors

### ISSUE THREAD

**Issue by cadrogui** [olexale/arkit_flutter_plugin#52]
Hi, first of all, thanks for share your work!!!...

currently i have a tensorflow model for foot detection, and i need is to attach a 3d model to the foot detected, or how can i set an anchor to a detected foot, this is because anchor use a vector3 and the tf model give me top and left position of the detected foot.

is this possible to achieve with this library?

regards.

**Comment by olexale** [comment]
Hi,

Yes, this should be possible. What is the exact output of your tesorflow model?

Kind regards

**Comment by olexale** [comment]
Closing as potentially not actual. Feel free to reopen this issue.
