### ISSUE TITLE
Add support for GLTF

### ISSUE THREAD

**Issue by lupohirp** [olexale/arkit_flutter_plugin#58]
Hello,

it's possibile to add support for GLTF through the GLTFSceneForm?

**Comment by olexale** [comment]
Hi,

I don't think gltf is supported by ARKit and for me GLTFSceneForm sounds like something from ARCore world.. Do you have an example of using gltf with arkit?

**Comment by lupohirp** [comment]
Sorry, i'm new to AR world and their framework/ formats, so maybe i'm sayin a no-sense thing. 
Howewer i found this : 

https://github.com/prolificinteractive/SamMitiAR-iOS

But, from your response, i understand that it's not possibile......

**Comment by olexale** [comment]
I would not say not possible, cause there is a 3rd-party dependency `GLTFSceneKit` which allows this. But yeah, currently it is not supported.
