### ISSUE TITLE
Identify detected image which was dynamically loaded

### ISSUE THREAD

**Issue by RedJ0hn** [olexale/arkit_flutter_plugin#59]
Hi. 
I have a question. I'm loading images to detect from firebase. I need to show different things to different images. Is any way to identify which image was just detected? I checked referenceImageName from anchor but it was null.
Thanks in advance for your help

**Comment by olexale** [comment]
Hi,
Fixed in 0.5.2. The`referenceImageName` field contains the same name you specified for url now. You may check it by using the plugin not via pub, but directly from git.
Thanks!
