### ISSUE TITLE
Cloud anchors support

### ISSUE THREAD

**Issue by opensourcegps** [olexale/arkit_flutter_plugin#63]
Hello,

is it possible to add support for Google's cloud anchors: https://developers.google.com/ar/develop/ios/cloud-anchors/developer-guide

or some hints how to do it?

Thanks!

**Comment by olexale** [comment]
Hi @opensourcegps ,

It seems that you need an [ARCore plugin](https://pub.dev/packages/arcore_flutter_plugin) instead. I don't think maintainers ported anchors already, but this might be a good feature request.

Kind regards,
Oleksandr

**Comment by opensourcegps** [comment]
@olexale thank for info. I've tried using cloud anchors on Android and it works. However to have iOS support one must add ARCore to ARKit and feed frames from ARKit to ARCore. Any hints how to do it?

**Comment by olexale** [comment]
I think it works in the opposite way: ARCore uses ARKit, not ARKit integrates ARCore in itself. Hence my best guess — you need to proceed with ARCore.
