### ISSUE TITLE
Question, display a flutter view over arkit view ?

### ISSUE THREAD

**Issue by jpsarda** [olexale/arkit_flutter_plugin#64]
That sounds like something very difficult to do but I have to ask. Would it be possible for example to track an image, and to display over this image a stretched flutter widget (strechted to fit the tracked image) ?

**Comment by olexale** [comment]
It is not as difficult as you think. :-) In fact, there is a [sample](https://github.com/olexale/arkit_flutter_plugin/blob/master/example/lib/widget_projection.dart), which does exactly that in this plugin.

Unfortunately, there is a problem — I messed up with math a bit, hence the result might be better. There are changes in a separate branch, which will simplify everything. I hope I'll get back to this sample later.

**Comment by jpsarda** [comment]
Wow, that looks awesome. Does the flutter widget receives the touch inputs ? Like you could show a video player for exemple and interact with it (play/pause the video) ?

**Comment by olexale** [comment]
yes, it is the same plain old flutter widget, which touches, navigation, etc.
