### ISSUE TITLE
Record camera question

### ISSUE THREAD

**Issue by gusabdala** [olexale/arkit_flutter_plugin#67]
Is there a way to record video? I'm currently using the `[camera plugin](https://pub.dev/packages/camera)` to record video but I want to be able to use arkit as well. Is this possible?

**Comment by olexale** [comment]
Unfortunately, I'm not aware of an easy way of doing that.
From the top of my head:

1. It is possible to get frames from the AR session, so it's possible to record video by sending frames to an `AVAssetWriter`. I would highly not recommend sending frames from native to Flutter side as when I tried that it either frame dropped or just froze a lot. 
If you're familiar with Swift you may want to have a look at [SceneKitVideoRecorder](https://github.com/svhawks/SceneKitVideoRecorder) for inspiration. I would recommend that way.
2. If you don't want to mess with frames by yourself, use `ReplayKit` from Apple. The main drawback is that it will record all controls as well, so you'll need to hide everything during the recording. The video quality might be limited as well, hence I would not recommend that way.

As this functionality is not the part of "vanilla ARKit" I'm closing the issue.
Thanks!

**Comment by gusabdala** [comment]
Thanks for the reply. Yea I’ve already integrated SceneKitVideoRecoreder into your plugin. It works but the quality of the video isn’t great. Still working on it though. Thanks again.

**Comment by Davidzhu001** [comment]
@gusabdala 
any solution?

**Comment by jtkeyva** [comment]
@gusabdala would you mind sharing your code to get video recording working?
thanks

**Comment by benMOOVENCY** [comment]
Hi @gusabdala  and @jtkeyva  did you find a solution to record the video via arkit_flutter_plugin ?

**Comment by jtkeyva** [comment]
> Hi @gusabdala and @jtkeyva did you find a solution to record the video via arkit_flutter_plugin ?

@benMOOVENCY no i have not. have you?

**Comment by AmrAbdelghany** [comment]
Hello guys, did anyone find a solution to record a video with AR objects? @gusabdala @jtkeyva @benMOOVENCY @Davidzhu001

**Comment by jtkeyva** [comment]
@AmrAbdelghany haven't tested it but this new package i just found looks promising:
https://pub.dev/packages/render

can't try it for a couple weeks. let us know if you give it a try and how it works
