### ISSUE TITLE
Question obtain camera position

### ISSUE THREAD

**Issue by jordanhart** [olexale/arkit_flutter_plugin#68]
Hi!

Flutter newb here. I am trying to figure out how to get the phone or camera position, in order to determine the distance away a point is from it. I so far have set ```worldAlignment: ARWorldAlignment.camera``` in ARKitSceneView, and took the distance from the point and the vector (0,0,0). Is it possible to obtain this information with this library? If so, is this a correct approach?

Thank you!

**Comment by olexale** [comment]
Hi!

Familiar question :) You may refer to this [code](https://github.com/olexale/arkit_flutter_plugin/issues/19#issuecomment-516878484).

Thanks!

**Comment by jordanhart** [comment]
Thank you!!!
