### ISSUE TITLE
Vertical Plane Detection

### ISSUE THREAD

**Issue by solosik** [olexale/arkit_flutter_plugin#71]
Thanks a lot for your work.

Could you please tell me if there're any examples of vertical planes detection, maybe even with placing objects etc.?

Is it possible at least?

Thank you in advance

**Comment by LucasTejero** [comment]
Hey,you can use the Horizontal Plane detection example
https://github.com/olexale/arkit_flutter_plugin/blob/master/example/lib/plane_detection_page.dart

you only have to change de line 29 from horizontal to vertical.

**Comment by olexale** [comment]
Thanks @LucasTejero !

@solosik , did you manage to get this working?

**Comment by solosik** [comment]
Thanks guys,

Yes, it works perfectly. 

Sorry, it seems that I missed a plane detection example.
