### ISSUE TITLE
FaceTracking in background

### ISSUE THREAD

**Issue by jordanhart** [olexale/arkit_flutter_plugin#72]
Hi again!

I am trying to run faceTracking and obtain face measurements while displaying a different, not camera widget. So far I found that it can be done with just making the current View invisible or rendered offscreen. I was wondering if there is more of a background friendly way for obtaining these measurements. Thank you so much for all your help!

Thank you so much!
Jordan

**Comment by olexale** [comment]
Hello!

Unfortunately, there is no "background friendly" way. Your approach with making the widget invisible seems good to me. 👍🏻

Kind regards,
Oleksandr

**Comment by jordanhart** [comment]
Thank you!
