### ISSUE TITLE
Google Sodar-like implementation

### ISSUE THREAD

**Issue by TJMusiitwa** [olexale/arkit_flutter_plugin#74]
Hey there awesome package. 
I'm trying to implement a distance area in the AR view, sort of, if not exactly similar to the Google **Sodar** , social distancing web app. 
If I am to get started which of the examples from this plugin is my best option to have this up and running either _measure distance_  or  _distance tracking_  ?
Many thanks.

**Comment by olexale** [comment]
Hi there! 

I don't think you need to measure the distance for this app. Instead, you may detect the ground and draw a 2m circle around your position. 
I'd started with `plane_detection` and `real_time_updates` samples instead.

Kind regards.

**Comment by olexale** [comment]
Feel free to re-open this issue if you still have any questions.
