### ISSUE TITLE
[Question] Detect and measure distance between points

### ISSUE THREAD

**Issue by James-A-White** [olexale/arkit_flutter_plugin#75]
Wow! What an amazing package you've created!

Here's my question: I would like to be able to detect two QR codes in the same frame and automatically measure the distance between them.  I've played with the image detection example, but after finding the anchor once, the onAnchorWasFound method is not called a second time if there are two similar images in the same frame.

Is what I'm trying to do possible with AR? I was hoping to be able to combine the image detection and measure distance examples into a single automated measuring capability.

Many thanks again!

**Comment by olexale** [comment]
Hey, thanks!

According to [documentation](https://developer.apple.com/documentation/arkit/detecting_images_in_an_ar_experience):

> ARKit adds an image anchor to a session exactly once for each reference image in the session configuration’s detectionImages array. If your AR experience adds virtual content to the scene when an image is detected, that action will by default happen only once. To allow the user to experience that content again without restarting your app, call the session’s remove(anchor:) method to remove the corresponding ARImageAnchor. After the anchor is removed, ARKit will add a new anchor the next time it detects the image.

Hope that helps!
