### ISSUE TITLE
[Question] How do i track an image (and update the anchor position)

### ISSUE THREAD

**Issue by vuk64** [olexale/arkit_flutter_plugin#78]
Hello,

i would like to track an image. For that i have to get the new anchor positions (or the position of the image) every X secounds. How do i do that?

Best Regards

**Comment by olexale** [comment]
Hi,
The good starting point would be to use the `imageTracking` configuration, which allows tracking up to four images simultaneously.
Could you share more details? What you are trying to achieve?
Kind regards

**Comment by vuk64** [comment]
Hi tanks for your response!

First of all i have a quick question: Is there any more documentaition aside this: https://pub.dev/packages/arkit_plugin ?

I have a business card, and want to have some more information (like a picture of me, a link to the website etc) pop up as soon as my card is recognized as image by the app.

The App already recognizes the card and spawn a small sphere at the position, but i have found no way that it (the sphere) can track the card if moved.

I hope you understand what i mean :)

**Comment by olexale** [comment]
I'm trying to follow Apple's API as close as I can, hence almost every Swift ARKit tutorial you'd see is useful for this plugin too.

Try setting the `imageTracking` configuration. The ARKit will not only track the device motion but handle your business card position changes as well.

**Comment by vuk64** [comment]
Hi, thanks for your response.
My current build looks like this:
`
class _MyImageTracker extends State<MyImageTracker> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ARKitSceneView(
          detectionImagesGroupName: 'AR Resources',
          onARKitViewCreated: (c) {
            c.onAddNodeForAnchor = (anchor) {
              if (anchor is ARKitImageAnchor) {
                final imagePosition = Vector3(
                  anchor.transform.getColumn(3).x,
                  anchor.transform.getColumn(3).y,
                  anchor.transform.getColumn(3).z,
                );
                final node = ARKitNode(
                  geometry: ARKitSphere(
                    radius: 0.06,
                    materials: [
                      ARKitMaterial(
                        diffuse:
                            ARKitMaterialProperty(image: "images/360foto.jpg"),
                        //doubleSided: true,
                        
                      )
                    ],
                  ),
                  position: imagePosition,
                );
                c.add(node);
              }
            };
          }),
    );
  }
}
`

The problem is i dont find any position where i can add "imageTracking"... Can you help me out?

**Comment by olexale** [comment]
Sure, it is in `ARKitSceneView`, so just add the line
```dart
 configuration: ARKitConfiguration.imageTracking,
```
right before `detectionImagesGroupName`.

**Comment by vuk64** [comment]
Thanks,

i added:
          configuration: ARKitConfiguration.imageTracking,
          //detectionImagesGroupName: 'AR Resources',
          trackingImagesGroupName: 'AR Resources',

to my build. While it still does find the image, the shpere position does not update :/

Any idea why that could be?

**Comment by vuk64** [comment]
SOLVED!

Thank you for your help, i got a (imo nicely) working solution!

For everybody who wants to achive the same thing, heres the code:

`import 'package:arkit_plugin/arkit_plugin.dart';
import 'package:arkit_plugin/widget/arkit_scene_view.dart';
import 'package:flutter/material.dart';
import 'package:vector_math/vector_math_64.dart';

class MyImageTracker extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _MyImageTracker();
  }
}

class _MyImageTracker extends State<MyImageTracker> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ARKitSceneView(
          configuration: ARKitConfiguration.imageTracking,
          trackingImagesGroupName: 'AR Resources',
          onARKitViewCreated: (c) {
            c.onUpdateNodeForAnchor = (anchor) {
              c.remove("MyNode");
              if (anchor is ARKitImageAnchor) {
                final imagePosition = Vector3(
                  anchor.transform.getColumn(3).x,
                  anchor.transform.getColumn(3).y,
                  anchor.transform.getColumn(3).z,
                );
                final node = ARKitNode(
                  name: "MyNode",
                  geometry: ARKitSphere(
                    radius: 0.06,
                    materials: [
                      ARKitMaterial(
                        diffuse:
                            ARKitMaterialProperty(image: "images/360foto.jpg"),
                      )
                    ],
                  ),
                  position: imagePosition,
                );
                c.add(node);
              }
            };
          }),
    );
  }
}`

Best Regards and thank you a lot! I like your work and will maybe contact you in the future if i have more questions :)
