### ISSUE TITLE
iPad Pro Lidar data

### ISSUE THREAD

**Issue by aytunch** [olexale/arkit_flutter_plugin#79]
Thanks for this great plugin. I need the Lidar data in order to make Geometric Scene Understanding. Do we already have it? Second question: are you planning on integrating a gemotric scene understanding plugin on top of this plugin for Flutter like this one: [Automatic Real Time Object Recognition - Apple iPad Pro LiDAR](https://youtu.be/S6Czok2Ztck) read the video info for more details.

**Comment by olexale** [comment]
Hey. I've already answered you on twitter, so just duplicate the answer here:
This project https://developer.apple.com/documentation/arkit/world_tracking/visualizing_and_interacting_with_a_reconstructed_scene… looks like a good starting point. Unfortunately, not all APIs are bridged yet. Still, it would be relatively easy to add them.
----
Feel free to open issues with requests in case you get stuck with plugin functionality.
Thanks!
