### ISSUE TITLE
Exception: Error running pod install

### ISSUE THREAD

**Issue by egemolu** [olexale/arkit_flutter_plugin#80]
Error output from CocoaPods:
↳
    /usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-core-1.9.3/lib/cocoapods-core/cdn_source.rb:342: warning:
    URI.escape is obsolete

    [!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified.
    Please specify a platform for this target in your Podfile. See
    `https://guides.cocoapods.org/syntax/podfile.html#platform`.

**Comment by olexale** [comment]
Hi! Have you set the minimum iOS version for your Flutter project?

**Comment by egemolu** [comment]
I

> Hi! Have you set the minimum iOS version for your Flutter project?

I dont think so

**Comment by olexale** [comment]
Well, that is the problem then. Try to set it to the latest one.

**Comment by egemolu** [comment]
> Well, that is the problem then. Try to set it to the latest one.

Thank you for you answers mate. Does it from podfile? There is a line # ios version =9.0
