### ISSUE TITLE
[feature request] 3d or 2d pose estimation front facing camera

### ISSUE THREAD

**Issue by jordanhart** [olexale/arkit_flutter_plugin#81]
Hi again!

I was wondering if it’s possible to obtain human pose estimation (3d or 2d) with the iPhone front facing camera with TrueDepth. I found an ARSkeleton concept, but didn’t find an example on it using this project.

Thank you so much!
Jordan

**Comment by olexale** [comment]
Hi Jordan,

Sorry, currently there is no sample for capturing body motions, but here is a good [tutorial from Apple](https://developer.apple.com/documentation/arkit/capturing_body_motion_in_3d), which might be adopted. I hope that helps.

Kind regards,
Oleksandr

**Comment by jordanhart** [comment]
Thank you!
