### ISSUE TITLE
[Question] How do i get the rotation of an image anchor

### ISSUE THREAD

**Issue by vuk64** [olexale/arkit_flutter_plugin#82]
Hello, its me again!

I am currently wondering how i can rotate an Plane. To be more specific, i dont understand how the Vector4() arguments work.

My goal is, that i have an image anchor which recgonizes the current rotation of the image, and than uses that rotation on a plane which is next to the image. 

Right now the plane is always floating perfectly straight, but i would like it to tilt if i tilt my image.

Thanks in advance and if you need any more information feel free to tell me! :)

**Comment by mochetti** [comment]
Hey there!

You can calculate the Euler angles (yaw, pitch and roll) from the anchor's rotation matrix. 
To get the rotation matrix, just use anchor.transform.getRotation(); and a Matrix3 should be returned. 
This is how a rotation matrix looks like:

![Screen Shot 2020-07-03 at 23 51 31](https://user-images.githubusercontent.com/17018148/86503832-4b9cf180-bd88-11ea-892a-3353c89ecd84.png)

I imagine the tilt angles are phi and psi. For a rotation matrix R, you get:

phi = atan(R[3][2] / R[3][3]);
psi = atan(R[2][1] / R[1][1]);

From here, you can update your node's angle using the node.eulerAngles.value property.

**Comment by vuk64** [comment]
Thanks for your answer, unfortuneatly i am not able to really use that.
Would it be possible that you provide me with a code sample?

**Comment by mochetti** [comment]
Hey!

Here I'm updating the node inside an onUpdateNodeForAnchor function.
```
void _handleUpdateAnchor(ARKitAnchor anchor) {

       // get the rotation matrix coordinates
       double r11 = anchor.transform.getRotation().entry(0, 0);
       double r21 = anchor.transform.getRotation().entry(1, 0);
       double r31 = anchor.transform.getRotation().entry(2, 0);
       double r32 = anchor.transform.getRotation().entry(2, 1);
       double r33 = anchor.transform.getRotation().entry(2, 2);

       // calculate the euler angles
       double rx = atan(r32 / r33);
       double ry = atan2(-1 * r31, r32 / sin(rx));
       double rz = atan(r21 / r11);

       // update your node
       yourNode.eulerAngles.x = rx;
       yourNode.eulerAngles.y = ry;
       yourNode.eulerAngles.z = rz;
}
```
You can see I'm using atan() for rx and rz just to avoid large steps in their values. You could use atan2() if the signals are managed properly.

Regards.

**Comment by vuk64** [comment]
Hi,

unfortuneatly this does not work for me :/ Nothings changes.

I am using the code below:

`
                // get the rotation matrix coordinates
                double r11 = anchor.transform.getRotation().entry(0, 0);
                double r21 = anchor.transform.getRotation().entry(1, 0);
                double r31 = anchor.transform.getRotation().entry(2, 0);
                double r32 = anchor.transform.getRotation().entry(2, 1);
                double r33 = anchor.transform.getRotation().entry(2, 2);

                // calculate the euler angles
                double rx = math.atan(r32 / r33);
                double ry = math.atan2(-1 * r31, r32 / math.sin(rx));
                double rz = math.atan(r21 / r11);

                print(rx);

                vector.Vector3 imageEuler = new vector.Vector3(rx, ry, rz);

                

                final node = ARKitNode(
                  name: "MyNode",
                  position: imagePosition,
                  //rotation: vector.Vector4(1, 0, 0, -math.pi / 2),
                  //rotation: imageRotation,
                  eulerAngles: imageEuler,`

Everytime i get a new anchor i delete the old node and create a new node on the position of the anchor. How do i get the rotation transfered on the node?

**Comment by olexale** [comment]
I hope that you already managed to get the rotation :) Starting from version 0.6.0 there is an easy way - there is an extension for `Matrix4` class, which exposes Euler angles. You may refer to `matrix4_ext.dart` file for details and implementation.

**Comment by YuxuanDu** [comment]
Thanks very much for your comment @olexale , I was struggling to get the right rotation until I saw this. Just wanted to share more information on how I made this correct:

(1) import the util mentioned:
`import 'package:arkit_plugin/src/utils/matrix4_ext.dart';`

(2) Get plane transform matrix
``` 
Matrix4 absTrans = createTransformMatrix(parentAnchor.transform,
            position, null, vector.Vector4(1, 0, 0, -math.pi / 2), null);
```
(3) Get Euler angle
`vector.Vector3 matrixEulerAngles = absTrans.matrixEulerAngles;`

Then, we should be able to set the matrixEulerAngles to node.
