### ISSUE TITLE
Facetracking in background with Offstage not working

### ISSUE THREAD

**Issue by jordanhart** [olexale/arkit_flutter_plugin#83]
Hi!

I am attempting to run facetracking in the background with Offstage. No matter what I do, it seems that the Arkit readings stops updating whenever I switch to a new screen. I put together a simple demo based on the facetracking demo in the link here [https://github.com/jordanhart/Arkit-measurement-readings-in-background-flutter](https://github.com/jordanhart/Arkit-measurement-readings-in-background-flutter) The project includes an iOS app with multiple tabs initialized with Offstage, and a print statement that prints updated values from facetracking. When switch tabs from the facetracking, the update stops, and starts again when switch back to the facetracking tab.

Would you have any advice on how to resolve the issue, or other methods for getting updated facetracking values with a different non camera widget showing and in focus. I so far also tried using an overlay. 

Thank you so much!
Jordan

**Comment by olexale** [comment]
Hello,

The AR view is bound with its widget lifecycle. Hence in order to keep it working, you may want to hide the widget, but keep it on screen. A stack with an opaque AR scene view should work.

Kind regards,
Oleksandr

**Comment by jordanhart** [comment]
Thank you! It turns out that a 0 opacity stops the measurement readings, but a very small opacity works. I updated the example in the repo listed above. 

Thank you again for all your help! Very much appreciate it!
Jordan
