### ISSUE TITLE
referenceImageName is null upon image detection

### ISSUE THREAD

**Issue by James-A-White** [olexale/arkit_flutter_plugin#84]
Hey! 

Thanks again for the great ARKit package!

I think I found a bug that makes multiple image detection very challenging to implement when using network images.  For the ARKitReferenceImage, I can only pass in a name and a width parameter. Since I'm using network image detection the name I'm passing is a URL (see image below).

![image](https://user-images.githubusercontent.com/5836474/86370266-c9290a80-bc7f-11ea-85cd-171043d0133c.png)

When the image is detected, the referenceImageName parameter is null, leaving me no way to determine which image has been detected (see screenshot below).

![image](https://user-images.githubusercontent.com/5836474/86369703-1ce72400-bc7f-11ea-9096-b8069baa64b0.png)

When I upload images into the XCode file directly and give them a name there, the name is properly passed back in the referenceImageName parameter.

Is this a bug or a limitation of Apple's ARKit software?

Thanks!

**Comment by olexale** [comment]
Hi! This issue should be already fixed in 0.5.2. Could you please check the dev build?

You may do this by changing the dependency to:
```yaml
dependencies:
  arkit_plugin:
    git: git://github.com/olexale/arkit_flutter_plugin.git
```

Thanks in advance!
Oleksandr
