### ISSUE TITLE
[Question] Change Material of SCNNode

### ISSUE THREAD

**Issue by stevedj** [olexale/arkit_flutter_plugin#9]
Hi Oleksandr Leuschenko,

Thank you for the amazing plugin,
I am trying to change the material when the user tap the plane,
my approach is to get the previous geometry, using _updateSingleProperty,
and rewrite the materials using new material, is it the right approach?

Best Regards
Steve

**Comment by olexale** [comment]
Hi Steve,

`UpdateSignleProperty` is a simple wrapper above Objective-C message sender. It assumes that the value is already in a format, which might be used with ARKit directly. In other words, it should work for numbers, but materials are complex structures. 

I've added a method which provides a possibility to change the materials list. Please see the updated "Tap" example with color change logic.

Oleksandr

**Comment by stevedj** [comment]
Hi Oleksandr,

amazing, I am trying it right now,
it is a great idea to put the onTap on the object,
let me check and get back to you

Best Regards
Steve

**Comment by stevedj** [comment]
Hi Oleksandr,

It is really working, amazing, thank you for your amazing plugin,

Best Regards
Steve

**Comment by olexale** [comment]
Thank you for testing! 

I plan to port the core ARKit functionality, but the whole framework is huge, so please do not hesitate to create issues in case you miss some functionality.

Oleksandr
