### ISSUE TITLE
How about Android?

### ISSUE THREAD

**Issue by adaskaliuk** [olexale/arkit_flutter_plugin#93]
It's planned to add Android supporting?

**Comment by olexale** [comment]
Hi Andrew,

No, as ARKit is not supported on Android devices. It makes sense to create a plugin, which will act as a facade to both this plugin and any ARCore implementation, but I'd fix all the issues of this plugin first.

Kind regards,
Oleksandr

**Comment by RobinLbt** [comment]
Hi @olexale, check out https://github.com/CariusLars/ar_flutter_plugin,
You could maybe give some feeback to the main contributor with your level of experience with AR
