### ISSUE TITLE
save screenshot?

### ISSUE THREAD

**Issue by sstadtl** [olexale/arkit_flutter_plugin#97]
is there any way to capture the AR scene from code?
This https://pub.dev/packages/screenshot
could not handle it.

**Comment by olexale** [comment]
Hi @sstadtl,
You may use [native_screenshot](https://pub.dev/packages/native_screenshot) plugin by @ivanjpg for that.

**Comment by sstadtl** [comment]
this work beautiful. ty 
![IMG_5761](https://user-images.githubusercontent.com/1283030/90504079-cbbcc200-e150-11ea-8580-f2803a39b47f.JPG)

**Comment by leeprobert** [comment]
That package will take a screenshot of the entire screen including any other widgets, app bars etc. Is there any way to grab the video frame from the `ARKitSceneView`? I would also like to just take the `UI.Image` data so I can allow my user to choose if they want to save it. I have tried `RepaintBoundary` technique but as pointed out, it doesn't seem to want to paint a video frame.

**Comment by leeprobert** [comment]
> Hi @sstadtl,
> You may use [native_screenshot](https://pub.dev/packages/native_screenshot) plugin by @ivanjpg for that.

I'd like to reopen this ... that alternative is not ideal. Surely we can grab a frame from the video?

**Comment by leeprobert** [comment]
`ARSession` has a `currentFrame` getter that returns an `ARFrame`. This class has a `capturedImage` property which is a `CVPixelBuffer` ... it would take a bit of work, but it should be possible to allow access to the `ARSession` and then convert that `CVPixelBuffer` into a `ByteArray` so we can create an image of it.

**Comment by leeprobert** [comment]
Not clear if `ARFrame` contains the augmented content as well, or just the raw video data.

**Comment by leeprobert** [comment]
the `snapshot` method of `ARSceneView` works and I have added it to the package as a `snapshot` method of `ARKitController`. I'll submit a pull request.
