### ISSUE TITLE
Urgent Widget as Node

### ISSUE THREAD

**Issue by egemolu** [olexale/arkit_flutter_plugin#99]
Hello Olex,
Do we have chance to add Widgets as ARKitNode when we detect an AR Reference Image ?

**Comment by olexale** [comment]
Hi @egemolu.

You may think of Flutter widgets as high-level entities. The abstraction is built in a way when high-level entities "know" about low-level, but not vice-versa. Node is a low-level entity, hence it may not operate widgets.

I suppose that what you really want is to apply AR Reference Image's transformations to the widget. This is possible. During my talk on Flutter Europe, in the last live coding, I implement this kind of behavior. It might be useful to review the `example` folder of the plugin as it's there as well.
